name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and upload APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          # The path to the buildozer.spec file.
          # Default: buildozer.spec
          # spec_file: buildozer.spec

          # The type of build to perform.
          # Options: debug, release, clean
          # Default: debug
          build_mode: debug

          # Whether to upload the generated APK as a workflow artifact.
          # Default: true
          # upload_artifact: true

          # The name of the artifact to upload.
          # Default: app-release
          artifact_name: BitLife-APK
